package com.myProjects.DTO;
// Generated 26 Jan, 2018 5:30:47 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Hsttransections generated by hbm2java
 */
@Entity
@Table(name = "hsttransections", catalog = "hmsystem")
public class Hsttransections{

	private int transId;
	private Hostlers hostlers;
	private String dateTime;
	private Integer type;

	public Hsttransections() {
	}

	public Hsttransections(int transId, Hostlers hostlers, String dateTime) {
		this.transId = transId;
		this.hostlers = hostlers;
		this.dateTime = dateTime;
	}

	public Hsttransections(int transId, Hostlers hostlers, String dateTime, Integer type) {
		this.transId = transId;
		this.hostlers = hostlers;
		this.dateTime = dateTime;
		this.type = type;
	}

	@Id

	@Column(name = "transID", unique = true, nullable = false)
	public int getTransId() {
		return this.transId;
	}

	public void setTransId(int transId) {
		this.transId = transId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID", nullable = false)
	public Hostlers getHostlers() {
		return this.hostlers;
	}

	public void setHostlers(Hostlers hostlers) {
		this.hostlers = hostlers;
	}

	@Column(name = "date_time", nullable = false, length = 25)
	public String getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(String dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
