package com.myProjects.DTO;
// Generated 26 Jan, 2018 5:30:47 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Parents generated by hbm2java
 */
@Entity
@Table(name = "parents", catalog = "hmsystem")
public class Parents{

	private ParentsId id;
	private Hostlers hostlers;

	public Parents() {
	}

	public Parents(ParentsId id, Hostlers hostlers) {
		this.id = id;
		this.hostlers = hostlers;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "firstName", column = @Column(name = "firstName", nullable = false, length = 20)),
			@AttributeOverride(name = "lastName", column = @Column(name = "lastName", nullable = false, length = 20)),
			@AttributeOverride(name = "contactNo", column = @Column(name = "contactNo", nullable = false, length = 10)),
			@AttributeOverride(name = "email", column = @Column(name = "email", length = 30)),
			@AttributeOverride(name = "password", column = @Column(name = "password", nullable = false, length = 30)),
			@AttributeOverride(name = "userId", column = @Column(name = "userID", nullable = false)) })
	public ParentsId getId() {
		return this.id;
	}

	public void setId(ParentsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID", nullable = false, insertable = false, updatable = false)
	public Hostlers getHostlers() {
		return this.hostlers;
	}

	public void setHostlers(Hostlers hostlers) {
		this.hostlers = hostlers;
	}

}
